using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Text;

namespace FacadePattern.Ebay.Model
{
    public static class CountryCode
    {
        public const string US = "United States";
        public const string AA = "APO/FPO/DPO";
        public const string CA = "Canada";
        public const string GB = "United Kingdom";
        public const string AF = "Afghanistan";
        public const string AL = "Albania";
        public const string DZ = "Algeria";
        public const string AS = "American Samoa";
        public const string AD = "Andorra";
        public const string AO = "Angola";
        public const string AI = "Anguilla";
        public const string AG = "Antigua and Barbuda";
        public const string AR = "Argentina";
        public const string AM = "Armenia";
        public const string AW = "Aruba";
        public const string AU = "Australia";
        public const string AT = "Austria";
        public const string AZ = "Azerbaijan Republic";
        public const string BS = "Bahamas";
        public const string BH = "Bahrain";
        public const string BD = "Bangladesh";
        public const string BB = "Barbados";
        public const string BY = "Belarus";
        public const string BE = "Belgium";
        public const string BZ = "Belize";
        public const string BJ = "Benin";
        public const string BM = "Bermuda";
        public const string BT = "Bhutan";
        public const string BO = "Bolivia";
        public const string BA = "Bosnia and Herzegovina";
        public const string BW = "Botswana";
        public const string BR = "Brazil";
        public const string VG = "British Virgin Islands";
        public const string BN = "Brunei Darussalam";
        public const string BG = "Bulgaria";
        public const string BF = "Burkina Faso";
        public const string BI = "Burundi";
        public const string KH = "Cambodia";
        public const string CM = "Cameroon";
        public const string CV = "Cape Verde Islands";
        public const string KY = "Cayman Islands";
        public const string CF = "Central African Republic";
        public const string TD = "Chad";
        public const string CL = "Chile";
        public const string CN = "China";
        public const string CO = "Colombia";
        public const string KM = "Comoros";
        public const string CD = "Congo, Democratic Republic of the";
        public const string CG = "Congo, Republic of the";
        public const string CK = "Cook Islands";
        public const string CR = "Costa Rica";
        public const string CI = "Cote d Ivoire (Ivory Coast)";
        public const string HR = "Croatia, Republic of";
        public const string CY = "Cyprus";
        public const string CZ = "Czech Republic";
        public const string DK = "Denmark";
        public const string DJ = "Djibouti";
        public const string DM = "Dominica";
        public const string DO = "Dominican Republic";
        public const string EC = "Ecuador";
        public const string EG = "Egypt";
        public const string SV = "El Salvador";
        public const string GQ = "Equatorial Guinea";
        public const string ER = "Eritrea";
        public const string EE = "Estonia";
        public const string ET = "Ethiopia";
        public const string FK = "Falkland Islands (Islas Malvinas)";
        public const string FJ = "Fiji";
        public const string FI = "Finland";
        public const string FR = "France";
        public const string GF = "French Guiana";
        public const string PF = "French Polynesia";
        public const string GA = "Gabon Republic";
        public const string GM = "Gambia";
        public const string GE = "Georgia";
        public const string DE = "Germany";
        public const string GH = "Ghana";
        public const string GI = "Gibraltar";
        public const string GR = "Greece";
        public const string GL = "Greenland";
        public const string GD = "Grenada";
        public const string GP = "Guadeloupe";
        public const string GU = "Guam";
        public const string GT = "Guatemala";
        public const string GG = "Guernsey";
        public const string GN = "Guinea";
        public const string GW = "Guinea-Bissau";
        public const string GY = "Guyana";
        public const string HT = "Haiti";
        public const string HN = "Honduras";
        public const string HK = "Hong Kong";
        public const string HU = "Hungary";
        public const string IS = "Iceland";
        public const string IN = "India";
        public const string ID = "Indonesia";
        public const string IE = "Ireland";
        public const string IL = "Israel";
        public const string IT = "Italy";
        public const string JM = "Jamaica";
        public const string JP = "Japan";
        public const string JE = "Jersey";
        public const string JO = "Jordan";
        public const string KZ = "Kazakhstan";
        public const string KE = "Kenya";
        public const string KI = "Kiribati";
        public const string KR = "Korea, South";
        public const string KW = "Kuwait";
        public const string KG = "Kyrgyzstan";
        public const string LA = "Laos";
        public const string LV = "Latvia";
        public const string LB = "Lebanon";
        public const string LI = "Liechtenstein";
        public const string LT = "Lithuania";
        public const string LU = "Luxembourg";
        public const string MO = "Macau";
        public const string MK = "Macedonia";
        public const string MG = "Madagascar";
        public const string MW = "Malawi";
        public const string MY = "Malaysia";
        public const string MV = "Maldives";
        public const string ML = "Mali";
        public const string MT = "Malta";
        public const string MH = "Marshall Islands";
        public const string MQ = "Martinique";
        public const string MR = "Mauritania";
        public const string MU = "Mauritius";
        public const string YT = "Mayotte";
        public const string MX = "Mexico";
        public const string FM = "Micronesia";
        public const string MD = "Moldova";
        public const string MC = "Monaco";
        public const string MN = "Mongolia";
        public const string ME = "Montenegro";
        public const string MS = "Montserrat";
        public const string MA = "Morocco";
        public const string MZ = "Mozambique";
        public const string NA = "Namibia";
        public const string NR = "Nauru";
        public const string NP = "Nepal";
        public const string NL = "Netherlands";
        public const string AN = "Netherlands Antilles";
        public const string NC = "New Caledonia";
        public const string NZ = "New Zealand";
        public const string NI = "Nicaragua";
        public const string NE = "Niger";
        public const string NG = "Nigeria";
        public const string NU = "Niue";
        public const string NO = "Norway";
        public const string OM = "Oman";
        public const string PK = "Pakistan";
        public const string PW = "Palau";
        public const string PA = "Panama";
        public const string PG = "Papua New Guinea";
        public const string PY = "Paraguay";
        public const string PE = "Peru";
        public const string PH = "Philippines";
        public const string PL = "Poland";
        public const string PT = "Portugal";
        public const string PR = "Puerto Rico";
        public const string QA = "Qatar";
        public const string RE = "Reunion";
        public const string RO = "Romania";
        public const string RU = "Russian Federation";
        public const string RW = "Rwanda";
        public const string SH = "Saint Helena";
        public const string KN = "Saint Kitts-Nevis";
        public const string LC = "Saint Lucia";
        public const string PM = "Saint Pierre and Miquelon";
        public const string VC = "Saint Vincent and the Grenadines";
        public const string SM = "San Marino";
        public const string SA = "Saudi Arabia";
        public const string SN = "Senegal";
        public const string RS = "Serbia";
        public const string SC = "Seychelles";
        public const string SL = "Sierra Leone";
        public const string SG = "Singapore";
        public const string SK = "Slovakia";
        public const string SI = "Slovenia";
        public const string SB = "Solomon Islands";
        public const string SO = "Somalia";
        public const string ZA = "South Africa";
        public const string ES = "Spain";
        public const string LK = "Sri Lanka";
        public const string SR = "Suriname";
        public const string SJ = "Svalbard";
        public const string SZ = "Swaziland";
        public const string SE = "Sweden";
        public const string CH = "Switzerland";
        public const string TW = "Taiwan";
        public const string TJ = "Tajikistan";
        public const string TZ = "Tanzania";
        public const string TH = "Thailand";
        public const string TG = "Togo";
        public const string TO = "Tonga";
        public const string TT = "Trinidad and Tobago";
        public const string TN = "Tunisia";
        public const string TR = "Turkey";
        public const string TM = "Turkmenistan";
        public const string TC = "Turks and Caicos Islands";
        public const string TV = "Tuvalu";
        public const string UG = "Uganda";
        public const string UA = "Ukraine";
        public const string AE = "United Arab Emirates";
        public const string UY = "Uruguay";
        public const string UZ = "Uzbekistan";
        public const string VU = "Vanuatu";
        public const string VA = "Vatican City State";
        public const string VE = "Venezuela";
        public const string VN = "Vietnam";
        public const string VI = "Virgin Islands (U.S.)";
        public const string WF = "Wallis and Futuna";
        public const string EH = "Western Sahara";
        public const string WS = "Western Samoa";
        public const string YE = "Yemen";
        public const string ZM = "Zambia";
        public const string ZW = "Zimbabwe";

        public static Dictionary<string, string> ToDict()
        {
            var countries = new Dictionary<string, string>();
            var constants = GetConstants(typeof(CountryCode));
            foreach (var country in constants)
            {
                countries.Add(country.Name, country.GetRawConstantValue().ToString());
            }

            return countries;
        }

        private static List<FieldInfo> GetConstants(Type type)
        {
            FieldInfo[] fieldInfos = type.GetFields(BindingFlags.Public | BindingFlags.Static | BindingFlags.FlattenHierarchy);

            return fieldInfos.Where(fi => fi.IsLiteral && !fi.IsInitOnly).ToList();
        }
    }
}